[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
goblin = { version = "0.10.4", default-features = false, features = [
    "elf64",
    "endian_fd",
    "alloc",
    "elf32",
    "mach32",
    "mach64",
] }
linked_list_allocator = "0.10.5"
spin = "0.10.0"
