[package]
name = "zedos-installer"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui.workspace = true
gpui-component.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_UI_Controls"] }

[build-dependencies]
embed-resource = "3.0.6"
