name: CI
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Install Dotslash
              uses: facebook/install-dotslash@latest

            - name: Install LLVM 22
              run: |
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh 22
                  sudo apt-get install -y clang-22 lld-22
                  echo "PATH=$PATH:/usr/lib/llvm-22/bin" >> $GITHUB_ENV

            - name: Install Rust
              uses: dtolnay/rust-toolchain@nightly
              with:
                  targets: aarch64-unknown-none-softfloat

            - name: Reindeer help
              run: ./tools/reindeer buckify

            - name: Build Kernel
              run: ./tools/buck2 build //src/kernel:kernel --target-platforms //platforms:kernel-arm64
